spring.application.name=reporte-service

spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db
spring.datasource.username=root
spring.datasource.password=b1d2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

